# Ключавой коды

In [ ]:
for i in input().split(','):
    --------------------------------------------
    
for _ in range(int(input())):
    --------------------------------------------
    
a, b = (int(i) for i in input().split())

------------------------------------------------
    
for i in iter(input, 'Аукцион закончен!'):
    i = i.split()
    
------------------------------------------------

for i in iter(input, '.'):
    --------------------------------------------
    

d = {i: [] for i in input().split(', ')}

------------------------------------------------

for k, v in d.items():
    --------------------------------------------
    
while b[0] != '.': 
    
------------------------------------------------

line = [i.strip('"') for i in line]

------------------------------------------------

N, M, M, P = [int(input()) for _ in 'NMKP']

------------------------------------------------
for i, j in enumerate(list1)

------------------------------------------------

print(', '.join(tasks) = print(*tasks, sep=", ")
      
------------------------------------------------

n, m = [int(input()) for i in 'nm']

------------------------------------------------
      
n, l = int(input()) * int(input()), []
      
------------------------------------------------
      
for _ in range(int(input())):
    for i in input().split():
      ------------------------------------------
      
nums = [int(item) for item in input().split()]
      
------------------------------------------------
      
N, M = map(int, input().split())
      
------------------------------------------------
      
d = {key:value for key,value in zip(x,y)}
      
------------------------------------------------

lat = [2,7,11,15]
for i, v in enumerate(lat):
    print(i, v)
      
------------------------------------------------
      
nums.sort(reverse = True)
      
------------------------------------------------
      
arr = set(range(1, len(nums)+1))
nums = set(nums)
return list(arr - nums)
------------------------------------------------
      
# to count the occurrence of each character:
      d[i] = d.get(i, 0) + 1
      
my_list = ['a', 'b', 'c', 'a', 'b', 'a', 'd']
counts = {}
for item in my_list:
    if item in counts:
        counts[item] += 1
    else:
        counts[item] = 1
      
------------------------------------------------
# to print dict key that has min or max value:
      min(d, key=d.get)
      
------------------------------------------------
rows = list(map(int, input().split()))
      
------------------------------------------------
keyboard = dict(zip(ids, rows))
      
------------------------------------------------
a.sort(key = len)
      
------------------------------------------------
a = [3, -4, 5, -6]
b = [1, 2, 3, 4]
sum(abs(x) for x in a)
18
sum(abs(x - y) for x, y in zip(a, b))
13
------------------------------------------------


In [5]:
#harf sanaydi
dic = {}
line = input()
for letter in line: 
    dic[letter] = dic.get(letter, 0) +1
print(dic)

MuhammadjonAbdulloh
{'M': 1, 'u': 2, 'h': 2, 'a': 2, 'm': 2, 'd': 2, 'j': 1, 'o': 2, 'n': 1, 'A': 1, 'b': 1, 'l': 2}


In [6]:
# udalit snak prepinaniya
import re
st = re.sub(r'[^\w\s]',' ',input()).split()
print(st)

Muhammadjon, Abdulloh!
['Muhammadjon', 'Abdulloh']


In [3]:
import re
text = input()
marks = '''!()-[]{};?@#$%:'"\,./^&*_'''
for x in text:
    if x in marks:
        ok = text.replace(x, "").replace(' ', '')
print(ok)

Muhammadjon, Abdulloh
MuhammadjonAbdulloh


In [2]:
a = 'Jane Macintosh LC520 5000'
a = a.split()
print(a)
print(', '.join(a))
print(''.join(a[1:-1]))
print(' '.join(a[1:-1]))

['Jane', 'Macintosh', 'LC520', '5000']
Jane, Macintosh, LC520, 5000
MacintoshLC520
Macintosh LC520


# Variables and strings

In [37]:
a='My first python code'
b="my second python code"
c="my first python code is 'Hello world', what is yours?"
math_string="6+5*3"
expression_string ="a+' '+b+' privet mir'"
print(math_string)
print(expression_string)
print(len(c))
print(a+' '+b+' '+c)
print(a.split(' '))
print(a.split('t'))
print(math_string.find('*'))
print(math_string.find('6'))
print(b.replace('o', 'i'))
print(eval(math_string))
print(eval(math_string+'1'))
print(eval(expression_string))

6+5*3
a+' '+b+' privet mir'
53
My first python code my second python code my first python code is 'Hello world', what is yours?
['My', 'first', 'python', 'code']
['My firs', ' py', 'hon code']
3
0
my secind pythin cide
21
161
My first python code my second python code privet mir


# Определения функция def

In [36]:
def asksituation():
    print('Whats up?')
    print('How r u?')
    print('What r u doing?')
asksituation()
print('tellmeplease!')
asksituation()

Whats up?
How r u?
What r u doing?
tellmeplease!
Whats up?
How r u?
What r u doing?


In [4]:
def square(x):
    print('Квадрат числа',x,'=',x**2)
square(9)   

Квадрат числа 9 = 81


In [17]:
for i in range(1,11):
    square(i)

Квадрат числа 1 = 1
Квадрат числа 2 = 4
Квадрат числа 3 = 9
Квадрат числа 4 = 16
Квадрат числа 5 = 25
Квадрат числа 6 = 36
Квадрат числа 7 = 49
Квадрат числа 8 = 64
Квадрат числа 9 = 81
Квадрат числа 10 = 100


In [18]:
def devide(a,b):
    print(a/b)
devide(40,5)
devide(525,5)

8.0
105.0


In [24]:
def even(a):
    if a%2==0:
        print(a,'четное')
    else:
        print(a,'нечетное')
for i in range(10,21):
    even(i)


10 четное
11 нечетное
12 четное
13 нечетное
14 четное
15 нечетное
16 четное
17 нечетное
18 четное
19 нечетное
20 четное


In [33]:
def factorial(n):
    произ=1
    for i in range(2,n+1):
        произ=произ*i
    print(произ)
factorial(6)

720


In [35]:
if 3>6:
    def primer():
        print('big')
else:
    def primer():
        print('little')
primer()

little


In [38]:
pi = float(3.14159)
print (pi)

3.14159


In [39]:
pi = int(3.14159)
print (pi)

3


# Print_volume

In [13]:
pi=3.141592653589793 or 22/7
r=float(input('Radius of share: '))
surarea=4*pi*r**3
volume=(4/3)*(pi*r**3)
print('Surface Area is: ',surarea)
print('Volume is:',volume)

Radius of share: 5
Surface Area is:  1570.7963267948965
Volume is: 523.5987755982987


# Volume of rectangle

In [17]:
length=int(input('Length of rectangle: '))
width=int(input('Width of rectangle: '))
height=int(input('Height of rectangle: '))
volume=length+width+height
print('Volume of a code=',volume)

Length of rectangle: 58
Width of rectangle: 44
Height of rectangle: 62
Volume of a code= 164


# Volume of cube

In [23]:
side=float(input('Inter the value of one side:'))
volume=(side*side*side)
print('The volume of the cube is:', volume)

Inter the value of one side:5
The volume of the cube is: 125.0


# Сумма ряда

In [4]:
a=int(input())
b=int(input())
s=0
for i in range(min(a,b),max(a,b)):
    s+=i
print(s)

1
10
45


# Цвета радуги

In [15]:
a=int(input())
color_rainbow=('Красный','Оранжевый','Желтый','Зеленый','Голубой','Синий','Фиолетовый')
if a<=7:
    for i in range(a):
        print(color_rainbow[i])
else:
    print("Радуга состоит только из семи цветов")
    


5
Красный
Оранжевый
Желтый
Зеленый
Голубой


# Ограниченный бюджет

In [4]:
a = int(input())
b = int(input())
for i in range(b):
    c = int(input())
    a = a-c
if a >= 0:
    print("Покупает")
elif a < 0:
    print("Не покупает")


6585
6
65
658
256
667
1111
1444
Покупает


# Сумма квадратов

In [9]:
a=int(input())
b=int(input())
c=0
for i in range(min(a,b),max(a,b)):
    c+=i**2
print(c)


2
6
54


# 12 месяцев

In [16]:
m=int(input())
months=('Первый месяц - январь', 'Второй месяц - февраль', 'Третий месяц - март', 'Четвертый месяц - апрель', 'Пятый месяц - май', 'Шестой месяц - июнь', 'Седьмой месяц - июль', 'Восьмой месяц - август', 'Девятый месяц - сентябрь', 'Десятый месяц - октябрь', 'Одиннадцатый месяц - ноябрь', 'Двенадцатый месяц - декабрь')
if m<=12:
    for i in range(m):
        print(months[i])
else:
    print("Error")

3
Первый месяц - январь
Второй месяц - февраль
Третий месяц - март


# Коровы

In [20]:
b=int(input())
for i in range(1,b+1):
    if 10<i<20 or 4<i%10<=9 or i%10==0:
        a=''
    elif i%10==1:
        a='а'
    elif 1<i%10<5:
        a='ы'
    print (f'На лугу {i} коров{a}')

7
На лугу 1 корова
На лугу 2 коровы
На лугу 3 коровы
На лугу 4 коровы
На лугу 5 коров
На лугу 6 коров
На лугу 7 коров


# Числа Фибоначчи

In [15]:
def fib(n):
    a=1
    b=1
    if n==1:
        return n
    else:
        print(a,end=' ')
        print(b,end=' ')
    for i in (range(2,n)):
        c=a+b
        a=b
        b=c
        print(c,end=' ')   
fib(8)


1 1 2 3 5 8 13 21 

In [11]:
n=int(input())
if n==0:
    print(0)
else:
    fib1= 0
    fib2 = 1
    for i in range(n):
        print(fib2, end=' ')
        fib1, fib2 = fib2, fib1 + fib2

8
1 1 2 3 5 8 13 21 

In [16]:
n=int(input())
a=1
b=1
if n==1:
    print(n)
else:
    print(a,end=' ')
    print(b,end=' ')
for i in (range(2,n)):
    c=a+b
    a=b
    b=c
    print(c,end=' ')

8
1 1 2 3 5 8 13 21 

In [17]:
a, b = 0, 1
for _ in range(int(input())):
    a, b = b, a + b
    print(a, end=' ')


8
1 1 2 3 5 8 13 21 

# "Простое" или "Составное" 

In [18]:
n = int(input())
for i in range(2,n):
    if n % i == 0:
        print('Составное')
        break
else:
    print('Простое')

35
Составное


# Таблица Пифагора

In [22]:
n=int(input())
for i in range(1,n+1):
    for a in range(1,n+1):
        print(i*a,end='\t')
    print()


10
1	2	3	4	5	6	7	8	9	10	
2	4	6	8	10	12	14	16	18	20	
3	6	9	12	15	18	21	24	27	30	
4	8	12	16	20	24	28	32	36	40	
5	10	15	20	25	30	35	40	45	50	
6	12	18	24	30	36	42	48	54	60	
7	14	21	28	35	42	49	56	63	70	
8	16	24	32	40	48	56	64	72	80	
9	18	27	36	45	54	63	72	81	90	
10	20	30	40	50	60	70	80	90	100	


In [24]:
n = int(input())
length = 0
while n > 0:
	n //= 10
	length += 1
print("Длина числа -", length)



559685
Длина числа - 6


In [1]:
def recurse(a):
    if (a == 0):
        print(a)
    else:
        recurse(a)

recurse(0)

0


In [2]:
if "Ni!":
    print ('We are the Knights who say, "Ni!"')
else:
    print ("Stop it! No more of this!")

We are the Knights who say, "Ni!"


In [4]:
percentage =  float ( 60 * 100) / 55
>>> print (percentage)

109.0909090909091


In [5]:
x = 5

if x % 2 == 1:

    print (x)

else:

    print (x, x%2)

5


In [11]:
def recurse(a):
    if (a == 1):
        print(a)
    else:
        recurse(a)

recurse(1)

1


In [13]:
n=int(input())
count=0
for i in range(n,2,-1):
    if n <= 0:
        count+=1
        print(count)
    else:
        print(n)

-3


In [19]:
def countup(n):
    if n >= 0:
        print('Blastoff!')
    else:
        print(n)
        countup(n+1)
countup(int(input()))

-3
-3
-2
-1
Blastoff!


In [4]:
def count(n):
    if n > 0:
        print(n)
        count(n-1)
     n<=0:
        if n!=0:
            print(n)
            count(n+1)
count(int(input()))

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 5)

In [ ]:
def countup(n):
    if n > 0 and n!=0:
        print(n)
        countup(n-1)
    elif n<0 and n!=0:
        print(n)
        countup(n+1)
countup(int(input(' Choose for yourself which function to call (countdown or countup):')))

In [7]:
n = 10
while n != 1:
    print (n,)
    if n % 2 == 0: # n is even
        n = n // 2
    else: # n is odd
        n = n * 3 + 1

10
5
16
8
4
2


In [8]:
n = 10000
count = 0
while n:
    count = count + 1
    n = n // 10
print (count)

5


In [10]:
while True:

    while 1 > 0:

        break

    print("Got it!")

    break

Got it!


In [11]:
"bib".find('b', 1, 2)

-1

In [1]:
my_list = [3, 2, 1]
print(my_list)

[3, 2, 1]


In [2]:
index = "Ability is a poor man's wealth".find("W")
print(index)

-1


In [3]:
for fruit in ["banana", "apple", "quince"]:
    print (fruit)

banana
apple
quince


In [4]:
mylist = ["now", "four", "is", "score", "the", "and seven", "time", "years", "for"]
a=0
while a < 8:
    print(mylist[a],)
    a = a + 2

now
is
the
time


In [6]:
mylist = [ [2,4,1], [1,2,3], [2,3,5] ]
total = 0
for sublist in mylist:
    total += sum(sublist)
print(total) 

23


In [7]:
index = "Ability is a poor man's wealth".find("w")
print(index)

24


In [8]:
my_list = [3, 2, 1]
print(my_list.sort())

None


In [9]:
pi = int(3.14159)
print (pi)

3


In [10]:
word = 'bAnana'

index = word.find('a')

In [11]:
if "Ni!":
    print ('We are the Knights who say, "Ni!"')
else:
    print ("Stop it! No more of this!")

We are the Knights who say, "Ni!"


In [12]:
def function2(param):
    print (param, param)
def function1(part1, part2):
    cat = part1 + part2
    function2(cat)
chant1 = "See You "
chant2 = "See Me "
function1(chant1, chant2)

See You See Me  See You See Me 


In [13]:
isinstance(10.001, float)

True

In [14]:
pi = float(3.14159)
print (pi)

3.14159


In [15]:

def area(l, w):
    temp = l * w
    return temp
l = 4.0
w = 3.25
x = area(l, w)
if ( x ):
    print (x)

13.0


In [17]:
x = 5
if x % 2 == 0:
    print (x)
else:
    print (x, x%2)

5 1


In [18]:
n = 10
while n != 1:
    print(n,)
    if n % 2 == 0: # n is even
        n = n / 2
    else: # n is odd
        n = n * 3 + 1

10
5.0
16.0
8.0
4.0
2.0


In [19]:
def print_n(s, n):
     if n > 0:
          print(s)
          print_n(s, n-1)
     return n
n = 3
while print_n("hi", n):
     print_n("there!", n)
     n = 0

hi
hi
hi
there!
there!
there!


In [20]:
def subroutine(n):
    while n > 0:
        print (n,)
        n -= 1

In [1]:
cash = int(input())
n = 0
while n <= cash:
    a = int(input())
    n += a
print("Стоп, Джон!")
print(n - a)


554
54
365
84
54
Стоп, Джон!
503


In [ ]:
a=int(input())


# Password

In [6]:
while True:
    p=input()
    if "1234" in p or "qwerty" in p:
        print ('Слабый пароль')
    elif len(p)<8:
        print ('Короткий пароль')
    elif p.isalpha():
        print ('Пароль должен содержать цифры')
    else:
        break

qwerty
Слабый пароль
12345678
Слабый пароль
sdfgggh
Короткий пароль
vcfddddddddddddddd
Пароль должен содержать цифры
Abdulloh571


In [8]:
a=4%5
print(a)

4


# НОД


In [9]:
n = int(input())
a = int(input())
for i in range(1, n):
    b = int(input())
    while b != 0:
        a, b = b, a % b
print(a)


3
12
33
9
3


In [11]:
import math
x = int(input())
nod = 0
for l in range(x):
    f = int(input())
    if nod == 0:
        nod = f
    else:
        nod = math.gcd(nod, f)
print(nod)

5
12
36
48
24
96
12


# Построение простых

In [1]:
from math import sqrt
m = int(input())
new_list = []
for i in range(2, m+1):
    for j in range(2, i):
        if j > int((sqrt(i)) + 1):
            new_list.append(i)
            break
        elif (i % j == 0):
            break
    else:
        new_list.append(i)
print(len(new_list))

14
6


In [2]:
def calc(x):
    y = 2
    while y * y <= x and x % y != 0:
        y += 1
    return(y * y > x)
z = int(input())
s = 0
for g in range(2,z+1):
    if calc(g) == True:
        s += 1
print(s)

14
6


In [ ]:
import sympy

n, counter = int(input()), 0
for i in range(n + 1):
    if sympy.isprime(i):
        counter += 1
print(counter)


In [7]:
n=int(input())
s=2
k=0
for i in range(2, n+1):
    s=2
    while s*s<=i and i%s!=0:
        s+=1
    if (s*s>i) is True:
        k+=1
print(k)

14
6


In [4]:
n = int(input())
d = 2
cnt = 0
for i in range(2, n + 1):
    d=2
    while d * d <= i and i % d != 0:
        d += 1
    if (d * d > i) is True:
        cnt += 1
print(cnt)

14
6


In [10]:
n=int(input())
for i in range (n):
    s=int(input())
 

if s*s<=i and i%s!=0:
    print('YES')
else:
    print('NO')


2
68
65
NO


# Olympiadnik Starter Pack

In [5]:
n = int(input())
c = [0] * n
for i in range(n):
    c[i] = int(input())
a, b = max(c), min(c)
while b != 0:
    a, b = b, a % b
print(a)
d = 2
while d * d <= a and a % d != 0:
    d += 1
print('YES' if d * d > a and a != 1 else 'NO')

6
64
51
42
90
13
169
13
YES


In [2]:
#eng kichkina 4 bn tugagan son
min = 30000
for i in range(int(input())):
    n = int(input())
    if n % 10 == 4 and n < min:
        min = n
print(min)

3
24
14
34
14


In [3]:
#6 sonini bulinuvchilarini yig'indisi
t=0
for i in range(int(input())):
    n = int(input())
    if n%6==0:
        t+=n
print(t)

3
12
25
6
18


In [ ]:
#obesneniya
map(int, input().split()) можно использовать в случае, если вводится несколько чисел через разделитель (в данном случае через пробел)

По шагам:
    
input() возвращает строку (например: "1 2 3")

split() преобразует строку в list по разделителю - по умолчанию это пробел (результат: ["1", "2" ,"3"])

map преобразует список в соответствие с функцией - в данном случае int(elem) (результат: [1, 2 , 3]
                                                                              

In [7]:
numbers = tuple(map(float, input().split()))
#eng katta va eng kichkina ikkita sosed sonni topish
s=0
for i in range(39):
    d=abs(numbers[i]-numbers[i+1])
    if d>s:
        s=d; a=numbers[i]; b=numbers[i+1]
print(a,b)

78.43 51.68 28.72 17.01 74.79 28.27 62.05 64.72 67.25 59.56 36.85 3.3 57.58 32.44 63.29 88.23 51.5 15.56 54.36 72.3 76.86 77.43 44.13 75.13 95.15 72.95 30.71 23.72 61.82 30.6 11.07 18.86 13.62 68.72 11.62 83.31 1.15 96.49 29.59 21.49
1.15 96.49


In [15]:
n="Muhammadjon Abdulloh"
print(list(n))
print(tuple(n))
print(n.split())
print("+".join(n))


['M', 'u', 'h', 'a', 'm', 'm', 'a', 'd', 'j', 'o', 'n', ' ', 'A', 'b', 'd', 'u', 'l', 'l', 'o', 'h']
('M', 'u', 'h', 'a', 'm', 'm', 'a', 'd', 'j', 'o', 'n', ' ', 'A', 'b', 'd', 'u', 'l', 'l', 'o', 'h')
['Muhammadjon', 'Abdulloh']
M+u+h+a+m+m+a+d+j+o+n+ +A+b+d+u+l+l+o+h


# X

In [ ]:
import numpy as np
# Заготовка под игровое поле. Символом "-" обозначается пустая клетка
board = np.zeros((3, 3)).astype(int)
inpt = input().split()
player1 = inpt[2]
bool_ = (not any(np.sum(board, 1) == 3), not any(np.sum(board, 0) == 3), not np.sum(np.diag(board)) == 3, not np.sum(np.flipud(board).diagonal(0)) == 3,      not any(np.sum(board, 1) == -3), not any(np.sum(board, 0) == -3), not np.sum(np.diag(board)) == -3, not np.sum(np.flipud(board).diagonal(0)) == -3)
while all(bool_):
    if inpt[2] == 'x':
        if board[int(inpt[0]) - 1, int(inpt[1]) - 1] == 0:
            board[int(inpt[0]) - 1, int(inpt[1]) - 1] = 1
            
            bool_ = (not any(np.sum(board, 1) == 3), not any(np.sum(board, 0) == 3), not np.sum(np.diag(board)) == 3, not np.sum(np.flipud(board).diagonal(0)) == 3,      not any(np.sum(board, 1) == -3), not any(np.sum(board, 0) == -3), not np.sum(np.diag(board)) == -3, not np.sum(np.flipud(board).diagonal(0)) == -3)
        if all(bool_):
            if 0 not in board:
                break
            inpt = input().split()
    else:
        if board[int(inpt[0]) - 1, int(inpt[1]) - 1] == 0:
            board[int(inpt[0]) - 1, int(inpt[1]) - 1] = -1
            
            bool_ = (not any(np.sum(board, 1) == 3), not any(np.sum(board, 0) == 3), not np.sum(np.diag(board)) == 3, not np.sum(np.flipud(board).diagonal(0)) == 3,      not any(np.sum(board, 1) == -3), not any(np.sum(board, 0) == -3), not np.sum(np.diag(board)) == -3, not np.sum(np.flipud(board).diagonal(0)) == -3)
        if all(bool_):
            if 0 not in board:
                break
            inpt = input().split()
if not all((not any(np.sum(board, 1) == 3), not any(np.sum(board, 0) == 3), not np.sum(np.diag(board)) == 3, not np.sum(np.flipud(board).diagonal(0)) == 3)):
    print('Игрок 1 победил' if player1 == 'x' else 'Игрок 2 победил')
elif not all((not any(np.sum(board, 1) == -3), not any(np.sum(board, 0) == -3), not np.sum(np.diag(board)) == -3, not np.sum(np.flipud(board).diagonal(0)) == -3)):
    print('Игрок 1 победил' if player1 == 'o' else 'Игрок 2 победил')
else:
    print('Ничья')


In [17]:
s = "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
#s[start:stop:step]
print(s[3]) # так мы обращаемся к четвертому элементу
print(s[1:]) # так мы отрезаем нулевой элемент строки (т. е. печатаем строку с первого элемента)
print(s[2:10]) # так мы вырезаем из строки подстроку со 2 по 9 символ включительно
print(s[3:11:2]) # так мы вырезаем из строки подстроку с 3 по 9 символ включительно с шагом 2
print(s[12:1:-1]) # так мы вырезаем из строки подстроку с 12 по 2 символ включительно (идем в обратном порядке)


e
orem ipsum dolor sit amet, consectetur adipiscing elit
rem ipsu
e pu
d muspi mer


In [1]:
#matematik belgi quyadi
ex=input()
l=list(map(int,ex.split()))
if l[0]*l[1]==l[2]:
    print (l[0],'*',l[1],'=',l[2])
elif l[0]/l[1]==l[2]:
    print (l[0],'/',l[1],'=',l[2])
elif l[0]+l[1]==l[2]:
    print (l[0],'+',l[1],'=',l[2])
elif l[0]-l[1]==l[2]:
    print (l[0],'-',l[1],'=',l[2])
else:
    print('Error')

571 63 634
571 + 63 = 634


In [2]:
#reklamada ishlatsa bularkan
num=int(input())
txt=input()
while txt!='.':
    print(txt[:num] + '... Читайте продолжение в источнике...' if len(txt) > num else txt)
    txt=input()

17
ШОК! Цены на бензин вырастут после летнего солнцестояния!
ШОК! Цены на бенз... Читайте продолжение в источнике...
.


# Generators

In [2]:
#first variant
a = []
for i in range(1, 11):
    a.append(i ** 2)
print(a)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [7]:
#second variant
#[<что положить в список> for <индекс/элемент> in <диапазон/итерируемый тип данных> if <условие>]
print([i ** 2 for i in range(1, 11)])



[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [9]:
#third exaple
#[<положить в список значение> if <условие> else <положить другое значение> for <индекс/элемент> in <диапазон/итерируемый тип данных>]
print([x ** 2 if x % 2 == 0 else 0 for x in range(1, 11)])

[0, 4, 0, 16, 0, 36, 0, 64, 0, 100]


In [10]:
dates = [1964, 2001, 2077, 1914, 1991]
# фильтрация дат
filtered = [date for date in dates if date > 1989]
print(filtered)

[2001, 2077, 1991]


# Faktorialov

In [2]:
def factorial(a, b):
    multiplier=1
    total=0
    for i in range(a,b):
        for j in range(2,i+1):
            multiplier*=j
            total+=multiplier
    print(total)
factorial(3,7)
#factorial(int(input()), int(input())

15090248


In [1]:
def factorial(a,b):
    b>a
    z = a-1
    x = 0
    s = 0
    for i in range(a,b+1):
        s = i*z
        z = s
        x+= s
    print(x)
factorial(int(input()), int(input()))

3
7
5910


# Konteneri ! 1,2

In [1]:
time,limit=list(map(int, input().split()))
kont=list(map(int, input().split(',')))
for i in range(time):
    kont=[j*2 for j in kont if j*2<=limit]
print(len(kont))

4 1500
320, 110, 37, 42, 277, 189, 99, 84
3


In [2]:
hours, limit = map(int, input().split())
boxes = map(int, input().split(", "))
for i in range(hours):
    boxes = [j * 2 for j in boxes]
    boxes = [j if j <= limit else 0 for j in boxes]
indx = []
max1 = boxes
for i in max1:
    if not i == 0:
        indx.append(max1.index(i) + 1)
print(*indx, sep = ', ')

4 1500
320, 110, 37, 42, 277, 189, 99, 84
3, 4, 8


In [2]:
def f(s = 0):
    return s
print(f(12))

12


a = '1,2,3,4'

print(int(a))

In [8]:
import pandas as f
dataframe = f.DataFrame()
dataframe['Name'] = [i for i in iter(input, '')]
dataframe['Age'] = [i for i in iter(input, '')]
dataframe['Accurancy'] = [i for i in iter(input, '')]
dataframe

Muhammad
nik

12
13

st
st



Name Age Accurancy
0  Muhammad  12        st
1       nik  13        st

In [ ]:
	
S1 + S2
Конкатенация (сложение строк)
S1 * 3
Повторение строки
S[i]
Обращение по индексу
S[i:j:step]
Извлечение среза
len(S)
Длина строки
S.find(str, [start],[end])
Поиск подстроки в строке. Возвращает номер первого вхождения или -1
S.rfind(str, [start],[end])
Поиск подстроки в строке. Возвращает номер последнего вхождения или -1
S.replace(шаблон, замена)
Замена шаблона
S.split(символы)
Разбиение строки по разделителю
S.isdigit()
Состоит ли строка из цифр
S.isalpha()
Состоит ли строка из букв
S.isalnum()
Состоит ли строка из цифр или букв
S.upper()
Преобразование строки к верхнему регистру
S.lower()
Преобразование строки к нижнему регистру
S.startswith(str)
Начинается ли строка S с шаблона str
S.endswith(str)
Заканчивается ли строка S шаблоном str
ord(символ)
Символ в его код ASCII
chr(число)
Код ASCII в символ
S.capitalize()
Переводит первый символ строки в верхний регистр, а все остальные в нижний
S.swapcase()
Переводит символы нижнего регистра в верхний, а верхнего – в нижний
S.lstrip()
Удаление пробельных символов в начале строки
S.rstrip()
Удаление пробельных символов в конце строки
S.strip()
Удаление пробельных символов в начале и в конце строки



In [ ]:
def check_variable():
    n=input()
    if n.isidentifier():
        print('Можно использовать')
    else:
        print('Нельзя использовать')
check_variable()

In [ ]:
def check_variable(n):
    while "Поработали, и хвтати" not in n:
        n=input()
        if n.isidentifier():
            print('Можно использовать')
        elif "Поработали, и хвтати" in n:
            break
        else:
            print('Нельзя использовать')
n = ''
check_variable(n)

In [2]:
def binary_to_decimal(n):
    # принимает строку (двоичная с. с.), возвращает число (десятичная с. с.)
    # ваш код
    return bin(n).replace('0b', '')

def decimal_to_binary(n):
    # принимает число (десятичная с. с.), возвращает строку (двоичная с. с.)
    # ваш код
    return int(n,2)

In [ ]:
def print_number():
    print(1443)
    print_number()

print_number()

1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443
1443


In [ ]:
def drink():
    print('Рецепт коктейля "Рекурсивный": '
          '20% спирта, 30% воды, 50% коктейля "Рекурсивный"...')
    drink()

drink()


Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Реце

Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Реце

Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Рецепт коктейля "Рекурсивный": 20% спирта, 30% воды, 50% коктейля "Рекурсивный"...
Реце

In [4]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(7))

5040


# Функция Аккермана

In [1]:
def A(m,n):
    if m == 0:
        return n+1
    elif m > n and n == 0:
        return A(m-1,1)
    elif m > 0 and n > 0:
        return A(m-1,A(m,n-1))
a=int(input())
b=int(input())
print(A(b,a))

2
3
29


# Сумма натуральных чисел до n


In [4]:
def recurcive_sum(n):
    if n==1:
        return 1
    else:
        return recurcive_sum(n-1)+n
recurcive_sum(4)

10

# Сумма всех чисел списка


In [2]:
def list_sum(lst):
    if len(lst)==0:
        return 0
    else:
        return lst[0]+list_sum(lst[1:])
print(list_sum([1, 2, 3, 4]))

10


# Проверка на палиндром


In [9]:
def palindrome(s):
    if len(s) < 2:
        return True
    else:
        return s[0] == s[-1] and palindrome(s[1:-1])
print(palindrome("радар"))

True


# Сумма цифр числа


In [8]:
def digits_sum(n):
    if n < 10:
        return n
    else:
        return n%10 + digits_sum(n//10)
print(digits_sum(1423))

10


# Числа Фибоначчи


In [14]:
def fib(n): 
    if n <= 2: return 1
    else: return fib(n-2) + fib(n-1)
print(fib(8))

21


In [15]:
def digits(n):
    # ваш код
    if len(str(n)) > 1:
        return str(n)[0] + " " + digits(int(str(n)[1:]))
    else: ""

In [7]:
cache={0: 0, 1: 1}
def fib(n):
    if n in cache: return cache[n]
    else:
        cache[n] = fib(n-1) + fib(n-2)
        return cache[n]
print(fib(42))

267914296


In [8]:
def subset(n):
    lst = ','.join(n)
    newlst = []
    if len(n) > 1:
        for i in range(len(n)):
            new = n[:i] + n[i + 1:]
        new = ','.join(new)
print(subset(list(input().split())))

1 2 3 4
None


In [1]:
def permute(items):
    length = len(items)
    def inner(ix=[]):
        do_yield = len(ix) == length - 1
        for i in range(0, length):
            if i in ix: #avoid duplicates
                continue
            if do_yield:
                yield tuple([items[y] for y in ix + [i]])
            else:
                for p in inner(ix + [i]):
                    yield p
    return inner()
for p in permute((items)):
    print(p)

NameError: name 'items' is not defined

In [2]:
def all_perms(elements):
    if len(elements) <=1:
        yield elements
    else:
        for perm in all_perms(elements[1:]):
            for i in range(len(elements)):
                # nb elements[0:1] works in both string and list contexts
                yield perm[:i] + elements[0:1] + perm[i:]
all_perms(3)

<generator object all_perms at 0x00000266B4D31900>

In [8]:
def generate_permutations(N:int, M:int=-1, prefix=None):
    ''' Генерация всех перестановок N чисел в M позициях с профиксок prefix 
    '''
M = N if M == -1 else M
prefix = prefix or []
if M == 0:
    print(*prefix)
    return
for number in range(1,N+1):
    if find(number, prefix):
        continue
    prefix.append(number)
    permutations(N, M-1, prefix)
    pefix.pop()
generate_permutations(3)

NameError: name 'M' is not defined

In [11]:
def perm(a, k=0):
   if k == len(a):
      print a
   else:
      for i in xrange(k, len(a)):
         a[k], a[i] = a[i] ,a[k]
         perm(a, k+1)
         a[k], a[i] = a[i], a[k]

print(a)

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a)? (Temp/ipykernel_1076/1037108393.py, line 3)

In [12]:
def permutation(items):
    if len(items) <= 1:
        yield items
    else:
        for nextItems in permutation(items[1:]):
            for i in range(len(nextItems) + 1):
                yield nextItems[:i] + items[0:1] + nextItems[i:]
permutation(3)

<generator object permutation at 0x00000266B4D567B0>

In [36]:
import itertools
for p in itertools.permutations(input()):
        print(' '.join(str(x) for x in p))

123
1 2 3
1 3 2
2 1 3
2 3 1
3 1 2
3 2 1


In [39]:
from itertools import permutations   
a = input()  
p = permutations(a) 
for j in list(p): 
    print(*j) 

123
1 2 3
1 3 2
2 1 3
2 3 1
3 1 2
3 2 1


In [9]:
def tower_of_hanoi(numbers, start, auxiliary, end):  
    if(numbers):  
        print('Move disk 1 from rod {} to rod {}'.format(start, end))  
        return
    tower_of_hanoi(numbers - 1, start, end, auxiliary)  
    print('Move disk {} from rod {} to rod {}'.format(numbers, start, end))  
    tower_of_hanoi(numbers - 1, auxiliary, start, end)  
  
tower_of_hanoi(4, 1, 2, 3)

Move disk 1 from rod 1 to rod 3


In [17]:
def solve_hanoi(n, start, stop):
    if n == 1:
        print("Перенести диск 1 с", start, "на", stop)
    else:
        temp = (6 - start) - stop
        solve_hanoi(n - 1, start, temp)
        print("Перенести диск", n, "с", start, "на", stop)
        res = (n - 1, temp, stop)
        return res
solve_hanoi(4, 1, 3)

Перенести диск 1 с 1 на 2
Перенести диск 2 с 1 на 3
Перенести диск 3 с 1 на 2
Перенести диск 4 с 1 на 3


(3, 2, 3)

In [1]:
def moves(n, x = 1, y =3):
    if n == 1:
        print(f'Переложит диск {n} со стержня номер {x} на стержень номер {y}')
    else:
        moves(n - 1, x, 6 - x - y)
        print(f'Переложит диск {n} со стержня номер {x} на стержень номер {y}')
        moves(n - 1, 6 - x - y, y)
 
disc_number = int(input('Введите количество дисков:'))
moves(disc_number)

Введите количество дисков:4
Переложит диск 1 со стержня номер 1 на стержень номер 2
Переложит диск 2 со стержня номер 1 на стержень номер 3
Переложит диск 1 со стержня номер 2 на стержень номер 3
Переложит диск 3 со стержня номер 1 на стержень номер 2
Переложит диск 1 со стержня номер 3 на стержень номер 1
Переложит диск 2 со стержня номер 3 на стержень номер 2
Переложит диск 1 со стержня номер 1 на стержень номер 2
Переложит диск 4 со стержня номер 1 на стержень номер 3
Переложит диск 1 со стержня номер 2 на стержень номер 3
Переложит диск 2 со стержня номер 2 на стержень номер 1
Переложит диск 1 со стержня номер 3 на стержень номер 1
Переложит диск 3 со стержня номер 2 на стержень номер 3
Переложит диск 1 со стержня номер 1 на стержень номер 2
Переложит диск 2 со стержня номер 1 на стержень номер 3
Переложит диск 1 со стержня номер 2 на стержень номер 3


In [ ]:
def tower_of_hanoi(numbers, start, auxiliary, end):  
    if(numbers):  
        print('Move disk 1 from rod {} to rod {}'.format(start, end))  
        return
    tower_of_hanoi(numbers - 1, start, end, auxiliary)  
    print('Move disk {} from rod {} to rod {}'.format(numbers, start, end))  
    tower_of_hanoi(numbers - 1, auxiliary, start, end)  
  
tower_of_hanoi(numbers, 'A', 'B', 'C')

# Iterating With for Loops in Python

In [2]:
values = ["a", "b", "c"]

for value in values:
    print(value)

a
b
c


In [3]:
index = 0

for value in values:
    print(index, value)
    index += 1

0 a
1 b
2 c


In [4]:
index = 0

for value in values:
    print(index, value)

0 a
0 b
0 c


In [5]:
for index in range(len(values)):
    value = values[index]
    print(index, value)

0 a
1 b
2 c


In [7]:
# working with enumerate():

for count, value in enumerate(values):
    print(count, value)

#When you use enumerate(), the function gives you back two loop variables:

#1) The count of the current iteration
#2) The value of the item at the current iteration

0 a
1 b
2 c


In [8]:
print(values[0])

a


In [9]:
for count, value in enumerate(values, start=1):
    print(count, value)

1 a
2 b
3 c


In [11]:
def check_whitespace(lines):
    """Check for whitespace and line length issues."""
    for lno, line in enumerate(lines):
        if "\r" in line:
            yield lno+1, "\\r in line"
        if "\t" in line:
            yield lno+1, "OMG TABS!!!1"
        if line[:-1].rstrip(" \t") != line[:-1]:
            yield lno+1, "trailing whitespace"

In [12]:
users = ["Test User", "Real User 1", "Real User 2"]
for index, user in enumerate(users):
    if index == 0:
        print("Extra verbose output for:", user)
    print(user)

Extra verbose output for: Test User
Test User
Real User 1
Real User 2


In [1]:
my_str = 'Discworld'
    my_str.startswith('Mad')  # False
    my_str.startswith('Disc')  # True
    my_str.startswith(('Disc', 'Mad'))  # True
    my_str.startswith('world', 4, 9)  # True

IndentationError: unexpected indent (Temp/ipykernel_2572/3442001858.py, line 2)

In [ ]:
 В разделе «str (строка)»: str.capitalize str.casefold str.center str.count str.decode str.encode str.endswith str.expandtabs str.find str.format str.format_map str.index str.isalnum str.isalpha str.isascii str.isdecimal str.isdigit str.isidentifier str.islower str.isnumeric str.isprintable str.isspace str.istitle str.isupper str.join str.ljust str.lower str.lstrip str.maketrans str.partition str.replace str.rfind str.rindex str.rjust str.rpartition str.rsplit str.rstrip str.split str.splitlines str.strip str.swapcase str.title str.translate str.upper str.zfill Форматирование при помощи % Форматные строки (f-string)

In [2]:
def check_skobk(a):
    lis = []
    for el in a:
        if el == "(":
            lis.append(el)
        else:
            if len(lis) >=1:
                lis.pop()
            else:
                print('No')
                exit()
    if len(lis) == 0:
        print('Yes')
    else:
        print('No')
check_skobk(input())

)(
No
No


In [1]:
>>> x = [1, 2, 3, 12, 15, 18]
>>> n = len(x)
>>> i = n//2
>>> x.insert(i, 50)
>>> print(x)

[1, 2, 3, 50, 12, 15, 18]


In [ ]:
from sketchpy import library as lib
obj = lib.rdj()
obj.draw()

# Модули.
    Таким образом, модуль – это любой файл, содержащий код на языке Python. Для Python термины “библиотека” и “модуль” равнозначны, в других языках программирования библиотекой может называться совокупность нескольких модулей.

Приведем пример использования модульного программирования:
	Допустим, мы написали ИИ, который за нас играет на трех биржах X, Y, Z. Скрипт отличается для каждой из бирж, поэтому каждый алгоритм вынесем в отдельную программу (модуль), а затем создадим файл main.py, который бы “собирал” все модули и запускал каждый скрипт. Тогда наш проект будет состоять из четырех файлов:
stock_X.py – алгоритм для игры на бирже X
stock_Y.py – алгоритм для игры на бирже Y
stock_Z.py – алгоритм для игры на бирже Z
main.py – основная программа. Она импортирует модули и может пользоваться их содержимым. Открыв проект, именно ее мы запустим, чтобы начать исполнение.

# Подключение и создание модуля
	Как уже было сказано, модулем является любая программа на языке Python. Но пока несколько программ не связаны программистом, они могут действовать только отдельно, используя только свои ресурсы. Создадим программу module.py:

def greet_user():
    print("Hello! I'm a brand-new module :3")
text = "Это очень важная строка, не потеряйте ее"

Этот модуль включает в себя всего одну функцию и одну переменную. Создадим файл main.py. Чтобы подключить созданный модуль, нужно использовать команду import <имя файла без расширения .py>. Чтобы использовать содержимое модуля, нужно обращаться к переменной/функции так: <имя модуля без расширения>.<имя объекта> – это так называемая “точечная нотация”.

import module
text = "\nСпасибо, что не потеряли"
print(module.text, text)  # переменные имеют одинаковое имя, но из-за точки проблем не возникает
module.greet_user()

Важно отметить, что Python будет искать модули, перечисленные после import, сначала в текущей папке, затем в папке, в которой установлен Python. Поэтому модули нужно создавать в той же папке, где планируется создать основную программу. 
Несколько модулей можно импортировать через запятую:

import module1, module2, ..., module_n

	Часто необходимо загружать не весь модуль, а только некоторые его компоненты. Если из большого модуля нам нужны несколько функций, нет необходимости загружать его целиком. Чтобы выборочно импортировать объекты модуля используют конструкцию

from <имя модуля> import <компонент1, компонент2, ..., компонентX>
	
    Доступ к объектам, импортированным таким образом, можно получить без точки. Например, мы могли бы написать в файле main.py:

from module import greet_user  # заметьте, что, импортируя функцию, мы не пишем круглые скобки
greet_user()

	В конструкции from … import можно импортировать и все объекты модуля:

from <имя модуля> import *
	
    Это позволит обращаться ко всем объектам модуля без использования точки. Однако это используется редко, так как может привести к проблемам. Например, если бы мы в первой версии программы main.py написали в начале from module import *, то у нас вместо двух переменных module.text и text оказались бы переменные text и text. Что произойдет, если попытаться напечатать их?
	Если названия модуля слишком длинное, то обращение ко всем объектам через точку может серьезно ухудшить читаемость или тратить Ваше время. В таких случаях при импортировании модуля можно указать его псевдоним с помощью слова as. Изменим main.py:
import module as m

text = "\nСпасибо, что не потеряли"
print(m.text, text)
m.greet_user()

# Стандартная библиотека Python
	Python содержит множество инструментов и, чтобы не напугать обилием функций и методов, многие из них были организованы в модули, которые подключаются при необходимости. Такие модули называются стандартными, потому что Вы можете их подключить сразу после установки Python и Вам не нужно самостоятельно создавать файлы или загружать эти модули со сторонних ресурсов. Возможно, Вы уже пользовались одной из стандартных библиотек, например, math. Вы можете просмотреть список доступных модулей, используя функцию help():

help("modules")

	Также с помощью функции dir Вы можете просмотреть все доступные объекты в модуле:

import math  # сначала нужно импортировать модуль
dir(math)

	Рассмотрим несколько модулей подробнее, чтобы проиллюстрировать работу со стандартной библиотекой.

https://docs.python.org/3/library/math.html

https://pythonworld.ru/moduli/modul-math.html

# Модуль random
	random позволяет генерировать случайные числа, выбирать случайные элементы и использовать различные распределения. 
	Документация к библиотеке: https://docs.python.org/3/library/random.html
	Инструкция на русском: https://pythonworld.ru/moduli/modul-random.html
	Напишем с помощью random небольшого бота, который смеется над Вашими шутками:

import random
responses = [":D", "Очень смешно!", "Ха-ха-ха", ")))", "Смешная шутка", "Довольно остроумно)"] 
joke = input()
while joke != ".":
    print(random.choice(responses))
    joke = input()

Также с помощью random можно проводить эксперименты. Например, проверим вероятности выпадения орла и решки после броска монетки:
import random
options = ["heads", "tails"]
heads = tails = 0
n = 10 ** 6
for i in range(n):
    flip = random.choice(options)
    if flip == "heads":
        heads += 1
    else:
        tails += 1
print(heads / n)
print(tails / n)

Без использования программирования провести миллион замеров было бы проблематично.

# Модуль collections
	Модуль collections вводит несколько новых структур данных на основе стандартных. Мы уже рассматривали этот модуль и объект deque в предыдущем дополнительном уроке. Кроме дека модуль содержит еще 8 структур данных, но мы для примера рассмотрим лишь один – Counter. При изучении Объектно-ориентированного программирования мы также познакомимся с namedtuple.
Документация: https://docs.python.org/3/library/collections.html
	Материал на русском: https://pythonworld.ru/moduli/modul-collections.html
	
Counter создан на основе словаря и позволяет подсчитать количество повторений элементов неизменяемого объекта. Допустим, мы хотим подсчитать количество повторений каждой буквы в слове. Мы могли бы использовать стандартный словарь:

d = {}
s = input()
for char in s:
    d[char] = d.get(char, 0) + 1
print(d)

	С использованием Counter, это делается проще:

from collections import Counter
print(Counter(input()))

	Также Counter включает несколько полезных методов: например, .elements(), .most_common(), а также между переменными типа Counter можно совершать некоторые математические действия:

from collections import Counter
a = Counter(input())
b = Counter(input())
print(a + b)
print(a - b)
print(a & b)
print(a | b)

	Задача “Грамматические запасы”
	Занимаясь разработкой, вы также можете встретить термины “фреймворк” и “API”. Узнать, чем они отличаются от “библиотеки” можно по ссылке: 

Разница между фрэймворком, библиотекой и API?
https://ru.stackoverflow.com/questions/585432/%D0%A0%D0%B0%D0%B7%D0%BD%D0%B8%D1%86%D0%B0-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-%D1%84%D1%80%D1%8D%D0%B9%D0%BC%D0%B2%D0%BE%D1%80%D0%BA%D0%BE%D0%BC-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%BE%D0%B9-%D0%B8-api

In [ ]:
math.ceil(x)
math.exp(x)
math.factorial(x)
math.pi
math.floor(x)
math.pow(x, y)
math.modf(x)
math.sin(x)
math.sqrt(x)
math.log2(x)

Округление вверх
Возвращает значение выражения e^x
Возвращает значение x!
Константа, обозначающая число π
Округление вниз
Возвращает x^y
Возвращает целую и дробную части числа
Вычисляет значение sin(x)
Вычисляет корень из числа x
Вычисляет логарифм x по основанию 2

In [7]:
import math
print(math.exp(5))


148.4131591025766


In [4]:
print(math.ceil(1/4))

1


In [5]:
print(math.floor(1/4))

0


In [6]:
print(math.factorial(0))

1


In [14]:
import mymodule
mymodule.greeting(input())

AttributeError: module 'mymodule' has no attribute 'greeting'

In [15]:
import mymodule
a = mymodule.aboutme["age"]
print(a)

AttributeError: module 'mymodule' has no attribute 'aboutme'

In [ ]:
import numpy as np
n, m = [int(i) for i in input().split()]
a = np.array([0]*m)
for i in range(n):
    s = np.array(input().split(), int) * (i + 1)
    a += s
print(a)

# Модуль pillow
	pillow – это библиотека для обработки изображений. pillow позволяет не только получать информацию о изображении, но и модифицировать картинку всевозможными способами.


In [8]:
from PIL import Image, ImageDraw, ImageFilter
from random import randint
image = Image.open("C:\Users\muham\Downloads\ic_python.png") # в кавычках указывается имя файла
image.show() # метод .show() откроет изображение


SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (Temp/ipykernel_10728/2517199322.py, line 3)

Параметры изображения:
	Создав переменную image, мы можем узнать некоторые параметры изображения – для обработки нам понадобятся размер изображения и массив пикселей. 
Справка: компьютер представляет изображение в виде матрицы пикселей, т. е. если размер изображения 600 * 400, то в матрице 400 строк и 600 столбцов. Каждый пиксель имеет свой цвет, так как он кодируется четырьмя числами от 0 до 255 – компонентами красного, зеленого и синего цветов (RGB), а также яркостью (A). Собирая изображение из тысяч пикселей разных цветов, компьютер отображает понятную человеку картинку. Таким образом, картинка – это матрица кортежей длины 3, или иначе – трехмерный массив.


In [4]:
#Получим параметры изображения:
width = image.width  # определяем ширину
height = image.height  # определяем высоту
pixels = image.load()  # выгружаем значения пикселей

NameError: name 'image' is not defined

In [5]:
draw = ImageDraw.Draw(image)
def get_new_color(color):
    new_color = color - randint(50, 100)  # для начала просто отнимем случайное число
    return max(new_color, 0)  # исключаем ситуацию, когда новый цвет стал меньше нуля
for i in range(width):
    for j in range(height):
        colors = pixels[i, j]  # получим кортеж (RGBA)
        red = colors[0]
        green = colors[1]
        blue = colors[2]
        new_red = get_new_color(red)
        new_green = get_new_color(green)
        new_blue = get_new_color(blue)
        # перерисуем в точке (i, j) пиксель с новыми компонентами (RGB)
        draw.point((i, j), (new_red, new_green, new_blue))
image.save("test.png")

NameError: name 'image' is not defined

In [6]:
def get_new_color(color):
    return 255 - color

In [11]:
image = Image.open('C:\Users\muham\Downloads\ic_python.png')
image = image.filter(ImageFilter.CONTOUR)
image.show()

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (Temp/ipykernel_10728/4280212680.py, line 1)

# Модуль numpy

План:

1. Способы задания массивов, их копирование

2. Булевы массивы

3. Изменение формы, размера массива

4. Индексация, разрезание, склеивание

5. Базовые операции над массивами

# Способы задания массивов, их копирование
    Как ранее говорилось, одним из важных отличий numpy-массивов от обычных списков является то, что все элементы массива имеют одинаковый тип данных. Основные типы данных в массивах: 

bool (логический тип)

int (целые со знаком)

float (действительные)

complex (комплексные, с этим множеством чисел вы познакомитесь в старших классах )

str (строки)

Мы не будем рассматривать все возможные типы данных (np.sctypes), так как от перечисленных выше они отличаются только размером в байтах (например,  int64, float32).
Создание массива можно выполнить различными способами. Первый из них (рассматривался на прошлом уроке) – преобразовать обычный Python-список или кортеж в массив:

import numpy as np

myArray1 = np.array([[1, 2], [3, 4]]) # array([[1, 2], [3, 4]])

myArray2 = np.array(((5, 6), (7, 8))) # array([[5, 6], [7, 8]])

myArray3 = np.array([1, 2, 3], dtype='float') # array([1., 2., 3.])

В данном примере особо интересен массив myArray3. Мы явно преобразовали изначально целочисленный список в массив с вещественными числами, поэтому после чисел теперь стоят точки.
Подумайте самостоятельно, а затем проверьте, какой вид будет иметь массив myArray4.

myArray4 = np.array([1.3, 2.5, 3.8, 4.0, -4.5, -3.9, -1.1], dtype='int32')

	Также можно создать массив указанного размера, заполненный нулями или единицами. В линейной алгебре часто встречаются единичные матрицы (в общем и целом, в нашем случае это двумерный массив), можно сказать, что это квадратная матрица из нулей, в которой на главной диагонали расположены единицы. 
  	Рассмотрим следующие примеры:

zerosArray = np.zeros((2, 2)) # array([[0., 0.], [0., 0.]]) 

onesArray = np.ones((3, 1)) # array([[1.],[1.],[1.]])

identityArray = np.eye(2) # array([[1., 0.], [0., 1.]]) ⇐ Единичная матрица

Подумайте и ответьте на вопрос: почему в последнем примере функция np.eye() принимает не кортеж, а одно целое число?
		
Еще один способ задать numpy-массив – с помощью функции np.arange(from, to, step). Тогда элементы массива будут принимать значения от from (включая) до to (не включая) с шагом step. 

A = np.arange(0, 1, 0.25) # array([0.  , 0.25, 0.5 , 0.75])

In [7]:
import numpy as np
myArray1 = np.array([[1, 2], [3, 4]]) # array([[1, 2], [3, 4]])
myArray2 = np.array(((5, 6), (7, 8))) # array([[5, 6], [7, 8]])
myArray3 = np.array([1, 2, 3], dtype='float') # array([1., 2., 3.])
print(myArray3)
myArray4 = np.array([1.3, 2.5, 3.8, 4.0, -4.5, -3.9, -1.1], dtype='int32')
print(myArray4)

zerosArray = np.zeros((2, 2)) # array([[0., 0.], [0., 0.]])

onesArray = np.ones((3, 1)) # array([[1.],[1.],[1.]])

identityArray = np.eye(2) # array([[1., 0.], [0., 1.]]) ⇐ Единичная матрица

[1. 2. 3.]
[ 1  2  3  4 -4 -3 -1]


In [11]:
# Рассмотрим следующие примеры:
zerosArray = np.zeros((2, 2)) # array([[0., 0.], [0., 0.]]) 
onesArray = np.ones((3, 1)) # array([[1.],[1.],[1.]])
identityArray = np.eye(2) # array([[1., 0.], [0., 1.]]) ⇐ Единичная матрица
print(zerosArray)
print(onesArray)
print(identityArray)

[[0. 0.]
 [0. 0.]]
[[1.]
 [1.]
 [1.]]
[[1. 0.]
 [0. 1.]]


In [13]:
A = np.arange(0, 20, 2)
print(A)

[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
a = np.identity(2, dtype=float)
print("Matrix a : \n", a)
# 3x3 matrix with 1's on main diagonal
b = np.identity(3)
print("\nMatrix b : \n", b)

Matrix a : 
 [[1. 0.]
 [0. 1.]]

Matrix b : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
import numpy as np 
a = np.arange(25).reshape(5, 5)
np.diagonal(a)
np.array([ 0,  7, 14, 21, 28])

array([ 0,  7, 14, 21, 28])

In [1]:
import numpy as np
N, M = map(int,input().split())
arr = np.array([list(map(int,input().split())) for i in range(N)])
n, m = map(int,input().split())
if (newarr.shape, newarr.size == N, M):
    print(arr.reshape(n, m))
else: 
    print("Невозможно")

2 3
54 4 5
6556 56 56
3 2
[[  54    4]
 [   5 6556]
 [  56   56]]


In [1]:
class Person:
  def __init__(self, fname):
    self.firstname = fname

  def printname(self):
    print(self.firstname)

class Student(Person):
  pass

x = Student("Mike")
x.printname()

Mike
